from django.conf.urls import url
from django.conf.urls.static import static
import views

urlpatterns = [ url(r'^$', views.LIndex, name='Life'),
                url(r'^addwelcome', views.Addwelcome, name='Addwelcome'),
                url(r'^submitwelcome', views.Submitwelcome, name='Submitwelcome'),
                url(r'^deletephrase/(?P<id>[0-9]+)$', views.Deletephrase, name='Deletephrase'),
                url(r'^addquote', views.Addquote, name='Addquote'),
                url(r'^submitquote', views.Submitquote, name='Submitquote'),
                url(r'^deletequote/(?P<id>[0-9]+)$', views.Deletequote, name='Deletequote'),
                url(r'^addactivity', views.Addactivity, name='Addactivity'),
                url(r'^addingactivity', views.Addingactivity, name='Addingactivity'),
                url(r'^completactivityflrp/(?P<id>[0-9]+)$', views.Completeactivityflrp, name='Completeactivityflrp'),
                url(r'^completactivityrepe/(?P<id>[0-9]+)$', views.Completeactivityrepe, name='Completeactivityrepe'),
                url(r'^completactivityremi/(?P<id>[0-9]+)$', views.Completeactivityremi, name='Completeactivityremi'),
                url(r'^completactivitydead/(?P<id>[0-9]+)$', views.Completeactivitydead, name='Completeactivitydead'),
                url(r'^submitflrp/(?P<id>[0-9]+)$', views.Submitflrp, name='Submitflrp'),
                url(r'^submitrepe/(?P<id>[0-9]+)$', views.Submitrepe, name='Submitrepe'),
                url(r'^submitremi_/(?P<id>[0-9]+)$', views.Submitremi_, name='Submitremi_'),
                url(r'^submitdead/(?P<id>[0-9]+)$', views.Submitdead, name='Submitdead'),
                url(r'^submitremi/(?P<id>[0-9]+)$', views.Submitremi, name='Submitremi'),
                url(r'^addvideo', views.Addvideo, name='Addvideo'),
                url(r'^submitvideo', views.Submitvideo, name='Submitvideo'),
                url(r'^thanks', views.Thanks, name='Thanks'),
                url(r'^more/(?P<unique_id>[0-9]+)$', views.More, name='Mor'),
                url(r'^delete/(?P<unique_id>[0-9]+)$', views.Delete, name='Del'),
                url(r'^delvid/(?P<id>[0-9]+)$', views.Delvid, name='Delvid'),
                url(r'^morevid/(?P<id>[0-9]+)$', views.Morevid, name='Morevid'),
                url(r'^done/(?P<unique_id>[0-9]+)$', views.Done, name='Done'),
                url(r'^addarticle', views.Addarticle, name='Addarticle'),
                url(r'^submitarticle', views.Submitarticle, name='Submitarticle'),
                url(r'^readarticle/(?P<id>[0-9]+)$', views.Read, name='Read'),
                url(r'^deletearticle/(?P<id>[0-9]+)$', views.Deletearticle, name='Delarticle'),
                url(r'^about/', views.About, name='About'),
                url(r'^addnote/', views.Addnote, name='Addnote'),
                url(r'^submitnote', views.Submitnote, name='Submitnote'),
                url(r'^donerep/(?P<unique_id>[0-9]+)$', views.Donerep, name='Donerep'),
                url(r'^login', views.Showlogin, name='Showlogin'),
                url(r'^submitlogin', views.Login, name='Login'),
                url(r'^logout', views.Logout, name='Logout'),
                url(r'^showallarticles', views.Showallarticles, name='Showallarticles'),
                url(r'^adddescision', views.Adddescision, name='Adddescision'),
                url(r'^submitdescision', views.Submitdescision, name='Submitdescision'),
                url(r'^editdescision/(?P<id>[0-9]+)/', views.Editdescision, name='Editdesc'),
                url(r'^adddescposneg/(?P<posneg>[0-9]+)/(?P<descid>[0-9]+)/(?P<optid>[0-9]+)$', views.Adddescposneg, name='Adddesc'),
                url(r'^submitoption/(?P<descid>[0-9]+)$', views.Submitoption, name='Submitoption'),
                url(r'^submitcriteria/(?P<descid>[0-9]+)$', views.Submitcriteria, name='Submitcriteria'),
                url(r'^showalldescisions', views.Showalldescisions, name='Showalldescisions'),
                url(r'^deleteofficial(?P<unique_id>[0-9]+)$', views.Delofficial, name='Delofficial'),
                url(r'^editdescription/(?P<unique_id>[0-9]+)$', views.Editdescription, name='Editdescription'),
                url(r'^editproperties/(?P<unique_id>[0-9]+)$', views.Editproperties, name='Editproperties'),

                ]

