# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome_phrase',
            old_name='text',
            new_name='phrase',
        ),
        migrations.AlterField(
            model_name='welcome_phrase',
            name='part_of_day',
            field=models.CharField(max_length=1),
        ),
    ]
