# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('deadday', models.CharField(max_length=20)),
                ('deadtime', models.CharField(default='0:00', max_length=5)),
                ('warningtime', models.CharField(max_length=5)),
                ('unique_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='float_repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('rep_hours', models.CharField(max_length=10)),
                ('last_occurence', models.DateField()),
                ('deviation', models.CharField(max_length=10)),
                ('unique_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=500)),
                ('silencedYorN', models.CharField(max_length=1)),
                ('activation', models.CharField(max_length=10)),
                ('unique_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('active_week_days', models.CharField(max_length=20)),
                ('remindtilldoneYorN', models.CharField(max_length=1)),
                ('remember_time', models.TimeField(default='7:00')),
                ('unique_id', models.CharField(max_length=10)),
            ],
        ),
    ]
