# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0004_deadline_float_repeat_reminder_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='silencedYorN',
        ),
        migrations.AddField(
            model_name='deadline',
            name='silencedyorN',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='float_repeat',
            name='silencedyorN',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='silencedyorN',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='repeat',
            name='silencedyorN',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='float_repeat',
            name='deviation',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='float_repeat',
            name='last_occurence',
            field=models.DateField(default='1997-10-22'),
        ),
        migrations.AlterField(
            model_name='float_repeat',
            name='rep_hours',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='activation',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='text',
            field=models.CharField(default='no text', max_length=500),
        ),
    ]
