# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0005_auto_20170206_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='No description', max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('htmlembedder', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadday',
            field=models.DateField(default='2022-10-22'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadtime',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='description',
            field=models.CharField(default='No descpription', max_length=500),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='unique_id',
            field=models.CharField(default='Zero', max_length=10),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='warningtime',
            field=models.IntegerField(default='48', max_length=5),
        ),
        migrations.AlterField(
            model_name='float_repeat',
            name='unique_id',
            field=models.CharField(default='Zero', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='unique_id',
            field=models.CharField(default='Zero', max_length=10),
        ),
        migrations.AlterField(
            model_name='repeat',
            name='unique_id',
            field=models.CharField(default='Zero', max_length=10),
        ),
    ]
