# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0006_auto_20170207_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='float_repeat',
            name='last_occurence',
            field=models.IntegerField(default=0),
        ),
    ]
