# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0007_auto_20170207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='warningtime',
            field=models.IntegerField(default='0', max_length=5),
        ),
    ]
