# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0008_auto_20170207_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadtime',
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadmonth',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadday',
            field=models.IntegerField(default='0'),
        ),
    ]
