# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0009_auto_20170207_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='silenced',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
