# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0011_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='last_occurence',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
