# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0012_repeat_last_occurence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('day_added', models.CharField(max_length=10)),
                ('silenced', models.CharField(max_length=1)),
                ('unique_id', models.CharField(default='Zero', max_length=10)),
                ('show_text', models.CharField(default='Today', max_length=20)),
            ],
        ),
    ]
