# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0013_daily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='silenced',
            new_name='silencedyorN',
        ),
    ]
