# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0014_auto_20170215_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='silencedyorN',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
