# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0015_quote_silencedyorn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DDnegative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DDpositive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Descision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('silencedyorN', models.CharField(default='N', max_length=1)),
                ('unique_id', models.CharField(default='Zero', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('crit_scores', models.CharField(max_length=100)),
                ('descision_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Descision')),
            ],
        ),
        migrations.AddField(
            model_name='ddpositive',
            name='Doption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Doption'),
        ),
        migrations.AddField(
            model_name='ddnegative',
            name='Doption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Doption'),
        ),
        migrations.AddField(
            model_name='dcriteria',
            name='descision_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Descision'),
        ),
    ]
