# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('days', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quickalarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
    ]
